name: weareneontest
favicon: null
layout_spectrum: 0.4843939880374819
typography_spectrum: 0.2749884072691202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcebd1'
    - '#878883'
    - '#aabda0'
    - '#4a584e'
    - '#041716'
  brandStrength: 0.8197153478395194
  lightness: 0.49403194338083267
  saturation: 0.429605397162959
  rhythmicContrast: 0.14449630514718592
purpose: []
